title = "Hafele-lock"
email = "chao.ye@hafele.com.cn"
description = "该网站展示了海福乐(Hafele)中国子公司(HPC)电子锁产品。旨在为客户提供一个方便快捷的渠道了解产品，下载资料，观看视频等。"
baseurl = ""
url = "https://dialock-hafele.netlify.app/"
twitter_username = "jekyllrb"
github_username = "jekyll"
remote_theme = "pmarsceill/just-the-docs@v0.3.3"
plugins = [ "jekyll-feed", "jekyll-admin" ]
logo = "/images/hafele-logo.jpg"
google_analytics = "GOOGLE_ACCESS_TOKEN"

[[contentful.spaces]]
[contentful.spaces.addons]
space = "SPACE_ADDONS_ID"
access_token = "SPACE_ACCESS_TOKEN"
