backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "/images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: add-on
    label: add-on
    files: "/images/uploads"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Link", name: "link", widget: "string"}